const adjectives = ['helpless', 'pastoral', 'frightening', 'fearless', 'ultra', 'annoyed', 'redundant', 'rigid', 'halting', 'worried', 'rare', 'neighborly', 'beneficial', 'furtive', 'imaginary', 'juicy', 'fluttering', 'sturdy', 'spicy', 'fine', 'nondescript', 'tight', 'jolly', 'squealing', 'grandiose', 'separate', 'splendid', 'stale', 'quizzical', 'damp', 'rapid', 'electric', 'interesting', 'sweet', 'abashed', 'stupid', 'malicious', 'warlike', 'brash', 'cowardly', 'barbarous', 'defeated', 'wiggly', 'gentle', 'cool', 'stupendous', 'foamy', 'wandering', 'irritating', 'penitent', 'hesitant', 'shrill', 'real', 'highfalutin', 'unable', 'smiling', 'frail', 'eager', 'mean', 'rude', 'efficient', 'foregoing', 'ill-informed', 'nutty', 'bored', 'gullible', 'untidy', 'happy', 'apathetic', 'fair', 'futuristic', 'literate', 'obeisant', 'able', 'groovy', 'momentous', 'materialistic', 'shaggy', 'shiny', 'creepy', 'whole', 'pumped', 'strong', 'outgoing', 'fast', 'peaceful', 'eight', 'rightful', 'sudden', 'fancy', 'dusty', 'macho', 'troubled', 'perpetual', 'nice', 'like', 'mature', 'unbiased', 'itchy', 'vivacious']

const animals = ['addax', 'alligator', 'aoudad', 'ape', 'argali', 'armadillo', 'baboon', 'badger', 'bison', 'blue crab', 'boar', 'budgerigar', 'buffalo', 'bull', 'bunny', 'burro', 'camel', 'canary', 'chimpanzee', 'civet', 'coati', 'colt', 'cow', 'dingo', 'donkey', 'dormouse', 'duckbill platypus', 'dung beetle', 'eagle owl', 'eland', 'elk', 'ewe', 'fawn', 'finch', 'fox', 'gazelle', 'gnu', 'goat', 'ground hog', 'guanaco', 'hare', 'hartebeest', 'highland cow', 'hippopotamus', 'horse', 'hyena', 'ibex', 'jerboa', 'kangaroo', 'kitten', 'koala', 'lion', 'llama', 'lovebird', 'lynx', 'mare', 'marmoset', 'mink', 'mole', 'monkey', 'moose', 'mule', 'musk-ox', 'newt', 'ocelot', 'octopus', 'okapi', 'opossum', 'otter', 'panda', 'parakeet', 'peccary', 'pig', 'porcupine', 'porpoise', 'prairie dog', 'pronghorn', 'puma', 'quagga', 'rabbit', 'raccoon', 'ram', 'salamander', 'seal', 'sheep', 'silver fox', 'skunk', 'snake', 'snowy owl', 'starfish', 'tapir', 'thorny devil', 'tiger', 'waterbuck', 'wildcat', 'wolf', 'wolverine', 'wombat', 'woodchuck', 'zebra']

const randomNick = () => (
  adjectives[Math.floor(Math.random()*adjectives.length)] + ' ' +
  animals[Math.floor(Math.random()*animals.length)]
)

export default randomNick
